/* Generated by tools/make-demo.py — do not edit by hand.

   Runs before app.js so the sample trip is already in storage by the time
   the app reads it. Seeds once; after that the demo behaves like the real
   app and remembers whatever you do to it. Open with ?reseed to start the
   sample over. */
(function () {
  var PREFIX = "tripspend.demo.";
  var MARK = PREFIX + 'seeded.v1';
  var TOPUPS = [[-2, "0810", "Donald", 80000], [-2, "0812", "Kwan", 25000], [-1, "0930", "Donald", 20000]];
  var ENTRIES = [[-4, "2015", "Donald", "Credit Card", "Transportation", 18240, "ITA Airways LHR-FCO", "Booking ref XK9P2"], [-2, "1105", "Donald", "Cash", "Transportation", 1400, "Leonardo Express", "Fiumicino to Termini"], [-2, "1340", "Donald", "Global Money", "Food", 3850, "Trattoria Da Enzo", "Lunch, 4 pax"], [-2, "1620", "Kwan", "Cash", "Household", 1290, "Farmacia", "Sunscreen and plasters"], [-2, "1705", "Kwan", "Cash", "Food", 960, "Gelateria Giolitti", ""], [-2, "1930", "Donald", "Credit Card", "Entertainment", 4800, "Colosseum", "Skip-the-line x2"], [-1, "0805", "Donald", "Cash", "Food", 680, "", "Caffe and cornetto"], [-1, "1015", "Donald", "Global Money", "Transportation", 7200, "Frecciarossa Roma to Firenze", ""], [-1, "1450", "Kwan", "Credit Card", "Shopping", 12400, "San Lorenzo leather market", "Bag for mum"], [-1, "1610", "Kwan", "Cash", "Kids", 2250, "", "Carousel and a toy"], [-1, "2010", "Donald", "Global Money", "Food", 6120, "Osteria dell'Enoteca", "Dinner"], [-1, "2145", "Donald", "Cash", "Household", 450, "", "Bottled water x6"], [0, "0845", "Kwan", "Cash", "Food", 1140, "Mercato Centrale", "Breakfast"], [0, "1030", "Donald", "Global Money", "Entertainment", 5200, "Uffizi Gallery", "Timed entry 10:30"], [0, "1320", "Donald", "Cash", "Transportation", 1800, "", "Taxi back to the hotel"], [0, "1640", "Donald", "Credit Card", "Shopping", 3590, "Pharmacy skincare", ""]];

  function pad2(n) { return (n < 10 ? '0' : '') + n; }

  function shift(days) {
    var d = new Date();
    d.setDate(d.getDate() + days);
    return d.getFullYear() + '-' + pad2(d.getMonth() + 1) + '-' + pad2(d.getDate());
  }

  // An ISO stamp on the given day at the given hhmm — only the ordering
  // within a day matters, and the records list sorts on createdAt.
  function stamp(days, hhmm) {
    var d = new Date();
    d.setDate(d.getDate() + days);
    d.setHours(+hhmm.slice(0, 2), +hhmm.slice(2), 0, 0);
    return d.toISOString();
  }

  var reseed = /[?&]reseed\b/.test(location.search);
  try {
    if (!reseed && localStorage.getItem(MARK)) return;
  } catch (e) { return; }

  var n = 0;
  var uid = function () { return 'demo-' + (++n); };

  var topups = TOPUPS.map(function (t) {
    return {
      id: uid(), schemaVersion: 2, date: shift(t[0]), amountMinor: t[3],
      currency: 'EUR', account: t[2],
      createdAt: stamp(t[0], t[1]), updatedAt: stamp(t[0], t[1]),
    };
  });

  var entries = ENTRIES.map(function (e) {
    return {
      id: uid(), schemaVersion: 2, date: shift(e[0]), amountMinor: e[5],
      currency: 'EUR', account: e[2], payment: e[3], category: e[4],
      description: e[6], remarks: e[7],
      createdAt: stamp(e[0], e[1]), updatedAt: stamp(e[0], e[1]),
    };
  });

  var put = function (k, v) { localStorage.setItem(PREFIX + k, JSON.stringify(v)); };
  put('settings.v1', { tripStart: shift(-2), tripEnd: shift(4), accounts: ['Donald', 'Kwan'] });
  put('topups.v1', topups);
  put('entries.v1', entries);
  put('sticky.v1', { account: 'Donald', payment: 'Cash' });
  // Backed up just now, so a fresh demo opens without the nag banner.
  put('lastBackup.v1', new Date().toISOString());
  localStorage.removeItem(PREFIX + 'bannerDismissed.v1');
  localStorage.setItem(MARK, '1');

  if (reseed) history.replaceState(null, '', location.pathname);
})();

// A badge on every screen, so a demo phone is never mistaken for the real
// one. Added from script to keep the copied markup identical to the app's.
document.addEventListener('DOMContentLoaded', function () {
  Array.prototype.forEach.call(document.querySelectorAll('.screen-title'), function (h) {
    var pill = document.createElement('span');
    pill.className = 'demo-pill';
    pill.textContent = 'DEMO';
    h.appendChild(pill);
  });
});
